### ISSUE TITLE
Remind is shit

### ISSUE THREAD

**Issue by alf1e** [Fripe070/FripeBot#42]
fix shitty remind

**Comment by Boxersteavee** [comment]
Agreed

**Comment by Fripe070** [comment]
can vouch

**Comment by alf1e** [comment]
> can vouch

fix?

**Comment by Fripe070** [comment]
If you’re unhappy with it, make a pull request  which improves it, it’s functional, so there isn’t anything to “fix”. Or if making a pull request is too much work, you could at the very least provide some basic suggestions on how to make it better, instead of just complaining.

**Comment by Boxersteavee** [comment]
https://media.discordapp.net/attachments/796492337789403156/1020080561248808990/Screenshot_20220915_221452.jpg

Details on the issue

**Comment by Dog-gamer124** [comment]
This isn't actually an issue with the bot, but with time.strptime() it raises ValueError when there is a 2 digit number in hour and 1 digit number in the minutes and seconds place.
![image](https://user-images.githubusercontent.com/81295020/190684572-fb903196-06d4-4d1d-81fd-e3a371a7f1d0.png)

**Comment by Dog-gamer124** [comment]
> https://media.discordapp.net/attachments/796492337789403156/1020080561248808990/Screenshot_20220915_221452.jpg
> 
> Details on the issue

"%H" only takes 0-23 as input which is why it's raising ValueError, I guess you could add "%d" but I dont really think its necessary. Or you could make a regex :)

**Comment by Fripe070** [comment]
Considering that reminders aren’t saved to disk along with the fact that the bot gets restarted quite often, having it wait for multiple days is really not feasible. If I want the bot to work with very long remind times, I’ll need to add a database (which I’ve already considered doing for things like storing tags).

**Comment by Fripe070** [comment]
(A json file doesn’t count as a database)
